### ISSUE TITLE
generate mesh worker service version matrix automatically 

### ISSUE THREAD

**Issue by freeznet** [streamnative/function-mesh-website#136]
- add a placeholder in mesh worker service doc for version matrix
- generate version matrix from mesh worker service repo via github action
- replace the placeholder when build the website

**Comment by freeznet** [comment]
```
git for-each-ref --shell --format="ref=%(refname)" refs/tags/ | while read entry ; do eval "$entry"; git cat-file -p $ref:pom.xml | yq -p xml '{.project.version: .project.properties["function-mesh.version"]}'; done
```

**Comment by Huanli-Meng** [comment]
Close this issue as FM Worker service is not open-sourced.
